"""add  clock_in as TTIMESTAMP to user_shifts, clock_in as TTIMESTAMP to user_shifts, nullable 

Revision ID: 689aab7a36e5
Revises: 
Create Date: 2024-02-15 11:47:16.358297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689aab7a36e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shifts', sa.Column('clock_in', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('user_shifts', sa.Column('clock_out', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shifts', 'clock_out')
    op.drop_column('user_shifts', 'clock_in')
    # ### end Alembic commands ###
